### ISSUE TITLE
Application Exception after installation of GCMZDrops

### ISSUE THREAD

**Issue by d3d9** [oov/aviutl_gcmzdrops#22] opened 2021-07-31 16:43 UTC
I want to use PSDToolKit, but I noticed that GCMZDrops makes AviUtl throw exceptions on launch.
It also happens when installing GCMZDrops on it's own, without the other PSDToolKit files.

I am using an English version of AviUtl, downloaded from https://nyaa.si/view/1310256.
According to the Version information in the Help menu it is based on Version 1.00.
Advanced Editing Plugin is Version 0.92.
I execute AviUtl using Locale Emulator so it uses Japanese locale.
The normal locale of my Windows 10 is English with UTF-8.

Without GCMZDrops installed, there are no exceptions thrown at startup.

With GCMZDrops installed:
First I get two exceptions related to chapter.auf and then one for GCMZDrops.auf.
When I move the chapter plugin to disable it, I still get the one exception for GCMZDrops.auf.

Example:
```
アドレス"0x0fddcbed"で例外"0xc0000005"が発生しました

発生モジュール : GCMZDrops.auf
オフセットアドレス : 0x0001cbed
備考 : FILTER::func_WndProc() [ごちゃまぜドロップス]

正常な動作が出来ない可能性がありますが処理を継続しますか？
```

I can provide you with the crash dump file or other information if it will help.
Thanks in advance for your help.

I hope it is acceptable that I am writing in English.
It's no problem if you want to answer in Japanese.

**Comment by oov** [comment] 2021-07-31 18:31
This plugin uses the name "拡張編集" to determine the existence of the plugin, but it stopped working because the plugin was renamed to "Advanced Editing".
In addition, there was a flaw in the process of displaying a error dialog.

I've fixed both issues in v0.3.20 so it should work.
Could you give it a try?

**Comment by d3d9** [comment] 2021-07-31 19:02
Thank you.
I do not get an exception anymore, but it displays an error message now (拡張編集プラグインが見つかりません).

I don't know a lot about the existing code or the programming language, but maybe it's because this exception always gets raised as the condition was commented out?

https://github.com/oov/aviutl_gcmzdrops/commit/6bdb1971037ea61b754e7e91aeccaf378fcc4f3e#diff-0f7ab9529e666b2ca985dbf3040909220f05361b093c21c6e41863e5a9a0cf3eR334

https://github.com/oov/aviutl_gcmzdrops/blob/6bdb1971037ea61b754e7e91aeccaf378fcc4f3e/src/lazarus/main.pas#L334

**Comment by oov** [comment] 2021-07-31 19:15
YOU ARE COMPLETELY RIGHT.
I'm sorry.
It fixed in v0.3.21.

**Comment by d3d9** [comment] 2021-07-31 19:26
Thanks again for the quick fix.
I am getting another error message now, 拡張編集のバージョンナンバー解析に失敗しました。

**Comment by oov** [comment] 2021-07-31 19:39
Oh, really?
It works as expected in my environment.

I would like to see a screenshot of the dialog that appears when select `Info` -> `Filter Plugin` from the main menu.

**Comment by d3d9** [comment] 2021-07-31 19:41
![image](https://user-images.githubusercontent.com/9254305/127750779-8b8c0e49-8aec-4701-8f6a-3ce4c0010b87.png)

**Comment by oov** [comment] 2021-07-31 19:57
Thank you.
Displayed content was as expected, there is no problem.

I changed my environment to UTF-8 mode and used the locale emulator too, but I haven't been able to reproduce the problem yet.
Please give me some time to think about it.

**Comment by d3d9** [comment] 2021-07-31 20:26
I think I found the source of this problem.
It's a tiny detail I forgot to mention. My locale isn't simply English, but English (Germany), so the meaning of comma and dot in numbers is switched. When I make . the decimal separator, there's no error message anymore. When I switch back to , as decimal separator, it appears again.

**Comment by oov** [comment] 2021-07-31 20:32
Nice!
I was able to reproduce the problem too.
I completely overlooked that possibility.

**Comment by oov** [comment] 2021-07-31 23:35
v0.3.22 has been uploaded.
I think this work even if the decimal separator is a comma.
Thank you for all your support!

**Comment by d3d9** [comment] 2021-08-01 00:10
Thank you very much.
There are no error messages from GCMZDrops anymore, and I tried out the functionality by dragging and dropping an image from the browser, which was successfully saved in the project directory and added as a layer.

However, maybe there are still some issues with PSDToolKit.
I don't see any objects created when dropping a PSD file in the Advanced Editing layers. The PSDToolKit window displays the PSD file correctly though.
Also when creating a PSDToolKit object manually in Advanced Editing, no object appears. So maybe this problem is not related to GCMZDrops anymore?
It would be nice if you could look into that when you have the time.

Thank you for your help. I am looking forward to using your software.

**Comment by oov** [comment] 2021-08-01 00:51
Yeah, I know PSDToolKit related problems are more complicated.

PSDToolKit uses * .exo file (exported object file) in various places.
We must prepare a completely different file because the item names in the * .exo file is changed by translation.
As a result, we will probably have to separate the distribution files for Japanese and English versions.
https://github.com/oov/aviutl_psdtoolkit/issues/87 will track this issue.

**Closed by oov** 2021-08-01 00:51 UTC
